services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    container_name: node_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MY_SQL_CONNECTION_STRING: mysql://myuser:mypassword@db:3306/mydatabase
    entrypoint: sh -c "sleep 10 && npm run start"
   
  frontend:
    build:
      context: ./frontend
    container_name: next_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mysql_data: